Document: amxa-puavomenu-extra
Title: Debian amxa-puavomenu-extra Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-puavomenu-extra is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-puavomenu-extra/amxa-puavomenu-extra.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-puavomenu-extra/amxa-puavomenu-extra.ps.gz

Format: text
Files: /usr/share/doc/amxa-puavomenu-extra/amxa-puavomenu-extra.text.gz

Format: HTML
Index: /usr/share/doc/amxa-puavomenu-extra/html/index.html
Files: /usr/share/doc/amxa-puavomenu-extra/html/*.html
